bundleRecipe:
  key: 'bundles:bundle'
  ingredients:
    items:
      S:
        type: STRING
      H:
        type: RABBIT_HIDE
    configuration: |-
      SHS
      H H
      HHH
  result:
    type: BUNDLE
    amount: 1
    display-name: ยง8Bundle
discoverOnJoin: true